name: CI_ONE

on:
  # schedule:
    # - cron: '* 3-10 * * 1-5'
  workflow_dispatch:
  push:
    paths:
      - 'script_one.rb'
      - '.github/workflows/ci_one.yml'

env:
  BOT: ${{ secrets.BOT }}
  CHAT: ${{ secrets.CHAT }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'
    - name: Run Script
      run: |
        npm i -g stock-nse-india
        yarn global add carbon-now-cli
        gem install telegram-bot-ruby
        nseindia equity MANDEEP | tee >(carbon-now --save-as=MANDEEP) | tee MANDEEP.txt
        nseindia equity MAXPOSURE | tee >(carbon-now --save-as=MAXPOSURE) | tee MAXPOSURE.txt
        nseindia equity APS | tee >(carbon-now --save-as=APS) | tee APS.txt
        ruby script_one.rb
    - name: Keep repository actions alive
      uses: gautamkrishnar/keepalive-workflow@v1
    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        token: ${{ github.token }}
        repository: ${{ github.repository }}
        retain_days: 0
        keep_minimum_runs: 1
