name: TG BOT API

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/tg_bot_api.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build telegram bot api
      run: |
        sudo apt-get update
        sudo apt-get upgrade
        sudo apt-get install make git zlib1g-dev libssl-dev gperf cmake clang-14 libc++-14-dev libc++abi-14-dev
        git clone --recursive https://github.com/tdlib/telegram-bot-api.git
        cd telegram-bot-api
        rm -rf build
        mkdir build
        cd build
        CXXFLAGS="-stdlib=libc++" CC=/usr/bin/clang-14 CXX=/usr/bin/clang++-14 cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX:PATH=/usr/local ..
        cmake --build . --target install
        cd ../..
        ls -l /usr/local/bin/telegram-bot-api*
    - name: Release telegram bot api
        uses: softprops/action-gh-release@v2
        with:
          name: Release
          fail_on_unmatched_files: true
          files: /usr/local/bin/telegram-bot-api*
